---
#
# This file contains the default configuration for puppet.
# Copy this file to /vagrant/build/vagrant.yaml and edit settings as please.
#
# Test your custom hiera config inside your vagrant box with:
#
#   hiera -c /vagrant/vendor/twentyfirsthall/vagrant-puppet/manifests/hiera.yaml <key>
#

#
# Apache
#

apache:
  log_level: 'error'

apache::mod::worker:
  startservers: 1
  serverlimit: 4
  maxclients: 16
  minsparethreads: 8
  maxsparethreads: 16
  threadsperchild: 32
  maxrequestsperchild: 256
  threadlimit: 32

apache::vhosts:
  vagrant:
    default_vhost: true
    port: 80
    docroot: '/vagrant/public'
    docroot_group: 'www-data'
    docroot_owner: 'www-data'
    serveraliases:
      - '*.ngrok.com'
    access_log: false
    directories:
      - path: '\.php$'
        provider: 'filesmatch'
        sethandler: 'proxy:unix:/var/run/php5-fpm.sock|fcgi://localhost'
      - path: '/vagrant/public'
        allow_override:
          - 'All'
        require: 'all granted'
        directoryindex: 'index.php index.html'

#
# PHP
#

php::extensions:
  xdebug:
    ini_changes:
      - 'set .anon/xdebug.remote_enable On'
      - 'set .anon/xdebug.remote_connect_back On'
      - 'set .anon/xdebug.idekey vagrant'
      - 'set .anon/xdebug.max_nesting_level 256'

#
# MySQL
#

mysql::server::root_password: 'vagrant'

mysql::server::override_options:
  mysqld:
    # Enforce utf8
    collation-server: 'utf8_unicode_ci'
    character-set-server: 'utf8'
    init-connect: 'SET NAMES utf8'

    # General
    bind-address: '0.0.0.0'
    performance_schema: 'ON'
    interactive_timeout: 300
    wait_timeout: 300

    # Safety
    max_allowed_packet: '16M'
    sql_mode: 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_AUTO_VALUE_ON_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY'

    # Caches and limits
    max_connections: 32

    # MyISAM
    key_buffer_size: '16M'

    # Inno
    innodb_file_per_table: 1
    innodb_buffer_pool_size: '64M'

mysql::databases:
  vagrant:
    user: 'vagrant'
    password: 'vagrant'
    host: '%'
    grant: 'ALL'
    enforce_sql: false
    # Optional default sql schema
    sql: '/vagrant/build/db-schema.sql'

#
# Extra puppet classes to include
#

classes:
  - 'core::bash'
  - 'nodejs'
  - 'phantomjs'
  - 'phpmyadmin'

#
# nodejs npm packages
#

nodejs:
  npm_packages:
    - bower
    - gulp
    - jshint
    - less
    - ngrok
    - uglify-js
    - uglifycss
